### ISSUE TITLE
Comments are removed on update

### ISSUE THREAD

**Issue by pwhittlesea** [helpermethod/dependency-update-maven-plugin#5]
It appears that this plugin uses the `XmlNodePrinter` to write out a pom.xml file which is indented with 4 spaces.

If you have no comments and are indented with 4 spaces then this is fine, however, I have quite a few comments in my pom.xml and I would guess not all `pom.xml` files are indented in a consistent way.

Would it be possible to update the pom.xml in a way similar to the [versions-maven-plugin](https://github.com/mojohaus/versions-maven-plugin) which leaves the rest of the `pom.xml` untouched?

**Comment by helpermethod** [comment]
This is a rather unfortunate side-effect of using Groovy's XML APIs, which remove comments and don't preserve formatting. Groovy once had a format-preserving API (DomUtil) but for some unknown reason removed it.

**Comment by helpermethod** [comment]
The versions-maven-plugin treats the pom.xml as text, which preserves the formatting but also results in tons of low-level string parsing code.

**Comment by helpermethod** [comment]
Maybe there is some alternative high-level lib which preserves both comments and formatting.

**Comment by pwhittlesea** [comment]
I'll see if I can find one. For me this is important as there is a copyright comment on the top of my `pom.xml` files which should not be removed.

Worst case I'm sure a simple SAX parser might suffice.

**Comment by sparsick** [comment]
Maybe this stackoverflow question and answer help you 

https://stackoverflow.com/questions/20690526/preserve-formatting-when-updating-xml-file-with-groovy

**Comment by helpermethod** [comment]
Hi @sparsick, thanks for the link. I've read the whole thread and it seems that JDOM would be the perfect tool for the job (preserves comments and formatting). I'll try to hack something this evening.

**Comment by helpermethod** [comment]
See https://groovyconsole.appspot.com/script/5123079931953152.

**Comment by helpermethod** [comment]
So it turns out preserving comments and indentation is possible using `DOMBuilder` and `DOMCategory`.

**Comment by helpermethod** [comment]
Hi @pwhittlesea, I've just released a new version (which should be available within the next few hours) which keeps comments and formatting.

It still rearranges the attributes of the `<project>` element, which will be fixed in the next release.

**Comment by helpermethod** [comment]
Closing the issue for now, as most of the problems seem to be resolved by using JSoup's XML Parser instead.
